import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Sidebar from "@/Components/Sidebare/Sidebar";
import Theme from "@/Components/Sidebare/theme/theme";

const roboto_init = Roboto({
  subsets: ["latin"],
  weight: "300",
});
export const metadata: Metadata = {
  title: "Abdelrhman Ammar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Theme>
        <body className=" dark:bg-black bg-blue-400 ">
          <div className="grid grid-cols-12 gap-6 px-5 my-14 lg:mb-0 md:mb-16 sm:px-20 md:px-32 lg:px-36 xl:px-48 ">
            <div className="h-full col-span-12 p-4 text-base text-center bg-white lg:col-span-3 rounded-2xl dark:bg-blue-500">
              <Sidebar />
            </div>
            <div className="flex flex-col col-span-12 bg-white rounded-2xl dark:text-white lg:col-span-9">
              Components
            </div>
          </div>
        </body>
      </Theme>
    </html>
  );
}
